### ISSUE TITLE
color flow issue

### ISSUE THREAD

**Issue by germancryo** [roddone/YeelightAPI#13]
Yeelight Firmware: 1.4.2_0061

Hi there,

I´m not able to get the ColorFlow work, here`s my code.

Device device = new Device("192.168.178.xxx");
ColorFlow colorFlow = new ColorFlow(0, ColorFlowEndAction.TurnOff);

colorFlow.Add(new ColorFlowRGBExpression(255,255,255,100, 1000));
colorFlow.Add(new ColorFlowRGBExpression(0, 0, 0, 0, 1000));

await device.Connect();
await device.SetPower(true);
await device.StartColorFlow(colorFlow);

await device.SetRGBColor(255, 102, 255); works just fine.

**Comment by roddone** [comment]
Hi, 

I think your second ColorFlowExpression is buggy because you try to set #000 color (black) with 0 brightness.  I assume your purpose is to turn off the device, if so, you have to stop the color flow and start a new one because native Yeelight API does not allow to turn off the device during a flow.

Does that workaround could solves your problem ?

Regards, 

Romain.

**Comment by germancryo** [comment]
Hi Romain,

thank you for your quick response.
Yes, this workaround did the trick.

Thank you for the great work,

Best regards,

Patrick
