### ISSUE TITLE
Question: is there a way to set a property?

### ISSUE THREAD

**Issue by lsoares** [roddone/YeelightAPI#28]
I'd like to set `active_mode`.  Something like:

`device.SetProp(PROPERTIES.active_mode, 0)`

(the use case is to swap between moonlight and daylight)

Would it make sense?

**Comment by roddone** [comment]
Not really, the properties are just the current state of the device and cannot be modified.  They are automatically updated when you use methode like "SetRgbColor", SetColorTemperature etc. (see https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf for more details).

YeelightAPI is just a .Net wrapper of Yeelight protocol. Of course we could create a "SetProp" method that calls the right API method depending of the property you want to change, but as I see it, this seems a lot of work (and lots of bugs to fix later 😂) for almost nothing.

Can you explain what is your use-case exactly ? Can't you just use the existing methods which are, by design, more intuitive than a "SetProp" method ?

**Comment by lsoares** [comment]
you're right. I read their PDF and I understood that to set the moonlight/daylight mode it's a bit weird - it's by setting the Power (?!). as you only have a wrapper I guess it makes sense. I did it using this way:

```
 await device.SetPower(true, null, PowerOnMode.Ct); // daylight
 await device.SetPower(true, null, PowerOnMode.Night); // moonlight

```
you can close this issue I guess. thanks!
