### ISSUE TITLE
[QUESTION] Is it possible to connect to the Yeelight device and send some commands from the device/application that is NOT in the same LAN?

### ISSUE THREAD

**Issue by mulykr** [roddone/YeelightAPI#34]
Is it possible to connect and send some commands to the bulb from the own web application hosted in Azure using this library?

**Comment by roddone** [comment]
That is a very interesting question and there is no simple answer to it, but I will try to expose you some ideas.
For the record, there is a cloud based solution proposed by Yeelight through the Mobile App, but Yeelight does not give any access to it to the developers.
As I mentionned several times before in other issues, YeelightAPI is "just" a wrapper around the [Yeelight protocol](https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf), and this protocol allows to connect directly to a bulb as long as you know it's IP/URL and port.
So the first answer should be "No, you can't".

But I think you should be able to communicate between LANs by setting your own mecanism to expose your Yeelight devices (e.g reverse proxy) between their LAN and Azure. But this approach could be a little risky since there won't be any security layer (yeelight devices calls are not secured) and your devices would be exposed to the web.

Another option would be to develop (in the same LAN as the devices) a middleware which role is to communicate bidirectionally between the devices and Azure (SignalR ?):
- Azure sends the commands to the middleware that dispatches them to the devices. 
- The middleware sends back to Azure devices states 
This way you can you can achieve communication through separate networks and set any security layer that you want. 
Personnaly, this second option is the one I chose at my home and it works very well, but it needs extra development you will have to do by yourself.

I hope I was able to help you, please let us know if any of these solutions works for you or if you found a better one !

**Comment by mulykr** [comment]
Thank you very much! I really appreciate your answer. Yes, I considered an option to develop some middleware and I think it should work as expected but just wanted to know if there is some way of direct communication.
So that, I will use the solution with bidirectional communication. Thank you!

Just one more question: is this API able to discover and communicate with all of the models of Yeelight?
