### ISSUE TITLE
[BUG] LED Ceiling Light brightness always returns 1 in moonlight mode

### ISSUE THREAD

**Issue by lsoares** [roddone/YeelightAPI#36]
**Describe the bug**
When in Moonlight mode, my Ceiling LED always returns brightness = 1
but the set works well from 1 to 100

**To Reproduce**
I have this code that proves the bug:

```
Console.WriteLine("curr value: " + await device.GetProp(PROPERTIES.bright)); // always 1
brightnessSlider.ValueChanged += async (sender, eventArgs) => {
     var value = Convert.ToInt32(Math.Round(eventArgs.NewValue));
     var x = await device.SetBrightness(value);
     Console.WriteLine("OK: " + x);
     Console.WriteLine("slider value: " + eventArgs.NewValue);
     Console.WriteLine("put value: " + value);
     Console.WriteLine("curr value: " + await device.GetProp(PROPERTIES.bright)); // always 1
}
````

**Expected behavior**
I'd expect the get brightness to change.
`device.GetProp(PROPERTIES.bright)` should return a value from 1 to 100

**Stacktrace**
```
{"FirmwareVersion":"22","Properties":{"power":"on","bright":"1","color_mode":"2","ct":"3200","rgb":"","hue":"","sat":"","name":"LED TV","flowing":"0","delayoff":"0","flow_params":"
","music_on":"","bg_power":"","bg_flowing":"","bg_flow_params":"","bg_ct":"","bg_lmode":"","bg_bright":"","bg_rgb":"","bg_hue":"","bg_sat":"","nl_br":"11","active_mode":"1"},"Suppo
rtedOperations":[1,8,6,7,5,11,12,13,14,9,10,2,17,15,30,31],"Hostname":"192.168.1.223","Id":"0x000000000805baaa","IsConnected":true,"Model":0,"Port":55443,"Name":"LED TV"}
```
When using the slider:
```
OK: True
slider value: 26
put value: 26
curr value: 1

OK: True
slider value: 61
put value: 61
curr value: 1
```

**Environment (please complete the following information):**
 - OS: Windows
 - .Net version .Net Core 3.1.102

**Comment by roddone** [comment]
I don't possess this kind of Yeelight device so I can't reproduce, but I don't think this is a bug, i think this is rather a lack of explanations about the night mode in Yeelight documentation.
According to the [yeelight documentation](https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf) there is a property named "nl_br" which means "Brightness of night mode light".

I assume this is this property that handles the brightness value in night mode. Can you try to get this property (PROPERTIES.nl_br) instead of PROPERTIES.bright ?

**Comment by lsoares** [comment]
You're correct! Thanks for the tip!
What's weird in their API is that you set moonlight and daylight with the same property.
But you get it with a different property.
