### ISSUE TITLE
[BUG] DeviceLocator throwing InvalidOperationException

### ISSUE THREAD

**Issue by LegendaryB** [roddone/YeelightAPI#39]
Hey,

I think I have discovered a bug in your library. The DeviceLocator.DiscoverAsync method throws an InvalidOperationException with the message: "Sequence contains no matching element"

I'm using this simple code to get all the devices:
`var devices = await DeviceLocator.DiscoverAsync();`

I'm using your library in an Xamarin application. There I get this exception even when I try with your sample code you used in the console sample app (DeviceLocator + Progress reporter)

Any ideas? And yes developer mode is activated on all devices ^^

**Comment by roddone** [comment]
Hi,

Can you please provide the stacktrace for the exception?

**Comment by LegendaryB** [comment]
Unfortunately no. The call stack is not displayed. Just [External Code]

Copied exception details:
```
System.InvalidOperationException
  Message=Sequence contains no matching element
```

```
The application is in break mode
Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code).
```

If it would help I could create a sample app to show the problem. Also didn't had the time yet to embed your library code directly into the app so that I can debug through it (I mean new project, adding your library as solution + app project)

**Comment by roddone** [comment]
There is something that comes to my mind, can you try to set the `DeviceLocator.UseAllAvailableMulticastAddresses = true;` before doing the call to `DeviceLocator.DiscoverAsync` ?

This is a parameter I had to add because of problems that occurs when dealing with Multicast addresses, specially in Xamarin projects.

**Comment by LegendaryB** [comment]
Sorry for my late response. Work was troublesome today^^
When I set the property to true the exception disappears. But the device enumeration is empty. By design it should be filled right? The normal Yeelight App is finding 2 bulbs.

**Comment by LegendaryB** [comment]
Now also the console app does not find my bulbs anymore. LAN control is enabled and the firmware is the newest version (2.0.6_0065)

**Comment by roddone** [comment]
The Yeelight App and the LAN (this API) are two separate things. 

The Yeelight App is using a proprietary cloud hosted mechanism to communicate with the bulbs. That's why you can use with cellular connection to control your bulbs.

The LAN (this API) uses direct wi-fi connection and communicates through UDP for the discovery, and TCP for controlling the bulbs.

What you can do to help identify the problem : 
1. Try to connect directly to your bulbs with their IP address (you can find it in the bulb settings in the App), if this does not work, your problem is more probably in your network configuration rather then the API
2. Try to discover devices in a simple console App (e.g YeelightAPI.Console), if this does not works either, you may have an issue in your router configuration.

For the records, Yeelight discovery uses SSDP like protocol on port 1982, you may want to check if this is allowed by your router.
More informations about the discovery protocol : [Yeelight_Inter-Operation_Spec](https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf)

**Comment by LegendaryB** [comment]
Yeah I know that. I also looked into the spec and know how it works. The direct connection via IP is working. The multicasts also because I have 2 other devices where I receive them. So it must be something else. Maybe its also a platform specific thing which is not working correctly on android. Unfortunately I can't test it on iOS because I don't have any apple hardware at home

EDIT: Console still works. Read somewhere that the Yeelight's stop sending or answering responses to multicast after some time when they are "spammed". Maybe this was yesterday evening the problem. Will try on android again

**Comment by roddone** [comment]
There is a limitation specified in the Yeelight specifications : 
`NOTE: Currently WiFi smart device support up to 4 simultaneous TCP connections, any further
connect attempt will be rejected. For each connection, there is a command message quota,
that is 60 commands per minute. There is also a total quota for all the LAN commands: 144
commands per minute 4 × 60 × 60%.`
I don't know if this has any impact on the discovery.

Let me know when you can test again on android.

**Comment by LegendaryB** [comment]
Tried it again on Android. Not working on android phone connected via wifi. Console app works. I think its maybe related to:
https://developer.android.com/reference/android/net/wifi/WifiManager.MulticastLock

**Comment by BionicCode** [comment]
This fix only fixes the algorithm to work without this internal exception being thrown. It does not fix the initial problem that `GetMulticastIPAddressesForDiscovery` fails to find multicast addresses. It may be because the `MulticastIPAddressInformationCollection` parameter is empty. In this case `NetworkInterface.GetIPProperties().MulticastAddresses` in `DeviceLocator.SearchNetworkForDevicesAsync` failed to retrieve any information. If this is the case, and I'm pretty sure it is, then this boils down to some network issues. Means the fact that the exception was thrown is a result of implementation details. But the origin of this exception is related to network or API setup. 

If you set `DeviceLocator.UseAllAvailableMulticastAddresses` to `true` as suggested, then the execution branch changes and `GetMulticastIPAddressesForDiscovery` invokes `Enumerable.Where`, which returns an empty collection if the predicate fails rather than throwing an exception (opposed to `Enumerable.First`).  
Again, the question is if the fact that there are no addresses are found, is really a bug and should be verified. Maybe the predicate is wrong/too narrow. Currently all address types of `AddressFamily.InterNetwork` are exclusively filtered. You should validate the filtering. @LegendaryB It would be interesting to know if the `multicastIPAddresses` parameter is empty or if it simply doesn't contain addresses of type `AddressFamily.InterNetwork`.

@LegendaryB You can generally attach a debugger to any running process. First start the application you wish to debug. Start Visual Studio. Go to _Debug/Attach to Process..._ in the menu. Select the process of the application and click on the _Attach_ button. Provoke the exception and then examine the stack trace and inner exceptions. Examine context variables like method parameters.

**Comment by nathanpovo** [comment]
I have run into this same issue when attempting to create a small Xamarin.Forms app for Android.

From what I understand, the issue seems to originate because all the `NetworkInterface` objects returned by the call to `NetworkInterface.GetAllNetworkInterfaces()` have no multicast IP addresses (the `MulticastIPAddressInformationCollection` collection of all `NetworkInterface` objects is always empty).

I have tested this out (both in the android emulator and on an actual android phone) using the example code in the [`NetworkInterface.GetIPProperties()`](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.getipproperties?view=netstandard-2.0) documentation page.

Testing the same code on a Windows 10 machine returns a lot of multicast IP addresses.

**Comment by nathanpovo** [comment]
Reading the Yeelight WiFi Light Inter-Operation Specification, it seems that getting all multicast IP address from all network interfaces is not needed. The specification indicates that `239.255.255.250:1982` is the only multicast IP address taken into consideration.

Is there any reason why all the trouble to get the multicast IP addresses was taken when there is only one possible value?

The `GetMulticastIPAddressesForDiscovery` method 
https://github.com/roddone/YeelightAPI/blob/8b8874a8380c5a60925ca28a838e75297783e13c/YeelightAPI/DeviceLocator.cs#L290-L309

seems to already use the `239.255.255.250` IP address by default but it is searching through the available multicast IP addresses to get it instead of simply using that address.

**Comment by roddone** [comment]
@nathanpovo I agree the yeelight documentations says `239.255.255.250:1982` is the only multicast address whe should take care of, but it appears it is not when dealing with Xamarin projects (and probably other use cases). Please take a look on #25 if you want extra details.
The thing is we had to add an option to allow using another specific multicast address or use all the multicast addresses availables. These options are disabled by default.

I've been busy lately and the next version including this fix would have been published for a long time, I apologize for that. I will manage to get the next version (1.10) released soon.

In a meantime, you can try the latest [pre-release version](https://www.nuget.org/packages/YeelightAPI/1.9.0-beta-CI-20201206-154359) and I would be glad to get your your feedback about this issue being fixed.

**Comment by nathanpovo** [comment]
I managed to work around the issue by modifying the `DeviceLocator` class to use the `IPAddress` class instead of the `MulticastIPAddressInformation` (which cannot be instantiated).

By using `IPAddress` I can then simply return the default multicast IP address from `GetMulticastIPAddressesForDiscovery` instead of searching through the addresses returned from `NetworkInterface.GetIPProperties().MulticastAddresses` (which, for reasons I don't understand, returns no addresses in a Xamarin Android app).

I can create a small pull request with the changes, if you want. Unfortunately, the latest pull request updated the `DeviceLocator` class so I'll go over the changes I made and re-apply them on top of the new additions.

> I've been busy lately and the next version including this fix would have been published for a long time, I apologize for that. I will manage to get the next version (1.10) released soon.

No rush, for now I have modified my own fork with changes so that I can build a quick Xamarin app for my own use. Thanks for your work on the library!
