### ISSUE TITLE
[QUESTION] Should I create new tcp connection on every http request or persist an exist one ?

### ISSUE THREAD

**Issue by PrzemyslawRodzik** [roddone/YeelightAPI#60]
Hi,
I integrate your awesome Yeelight API with my .NET 6 Web API. I create new Yeelight device and make a connection only once (yeelight device object is stored as property of YeelightDeviceService class (singleton). I've noticed that if I don't use the device for a long time, I get a "Broken pipe" error when I try to run a command.
Should I keep the connection or on every http request establish a new connection then invoke the command and terminate the tcp connection? 
Could you advise me on what I should do.

**Comment by roddone** [comment]
Hi, thank you for your interest in YeelightAPI.

A broken pipe can have multiple reasons, but in your case it's most likely because the device itself closes the connection after a certain elapsed time. Eventually the automatic reconnection mechanism included in the library may not be enough to handle this case.
It's difficult to give you an accurate answer because I don't know what is the purpose of your Web API or what kind of architecture you're buidding. But I understand the choice of declaring your service as a Singleton, probably for performance reasons, but in your case you may want to use a soped service (if you're using DI) or regularily create a new instance of the Device (MemoryCache can help you).
Also keep in mind that Yeelight Devices support 4 simultaneous TCP connections (doc : 
![image](https://user-images.githubusercontent.com/34140141/204082693-b9926c1d-7b65-48d4-beb7-a76b8e8b740d.png)
)

Good luck !
